//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ExpenseID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public string ExpenseDescription { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
