//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesignOfficeEntities : DbContext
    {
        public DesignOfficeEntities()
            : base("name=DesignOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientDetails> ClientDetails { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<EmployeeDepartments> EmployeeDepartments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<ProjectAssignments> ProjectAssignments { get; set; }
        public virtual DbSet<ProjectMaterials> ProjectMaterials { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<SaleItems> SaleItems { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TimeLogs> TimeLogs { get; set; }
    }
}
