//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignments
    {
        public int ProjectAssignmentID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public string Role { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
